version: "3"
services:
  login-app:
    container_name: node-express-test
    image: gsheeley/node-express
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    links:
      - test-mongo
    depends_on:
      - test-mongo
    command: "npm test"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
      MONGO_URL: "mongodb://127.0.0.1:27018/?authSource=admin"
      NODE_ENV: "dev"
  test-mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'